### ISSUE TITLE
Link to download RAW data does not work.

### ISSUE THREAD

**Issue by fjug** [IVRL/w2s#10]
Hi W2S crowd,

thanks a lot for your great work.
We happen to have trouble downloading the data from the link you provide in the README.md.
(https://datasets.epfl.ch/w2s/W2S_raw.zip)

Can you check and potentially resolve the issue?

Thanks a lot,
Best,
Floiran

**Comment by ManuBN786** [comment]
I'm facing the same issue.

How did you fix it ?

**Comment by majedelhelou** [comment]
Hello,

We are getting such issues also reported on other repositories with the same hosting platform, the problem is likely from there, unfortunately out of our reach. 
You can contact the support team of the hosting platform here: [EPFL IC IT](https://www.epfl.ch/schools/ic/it/en/organisation-du-support-informatique/), email: [support-icit@epfl.ch](mailto:support-icit@epfl.ch)
Connected lab at EPFL: IVRL

Hope the team will be able to sort it out for you quickly!

**Comment by ManuBN786** [comment]
Don't download from the web browser.
Instead write a code to download from the link

```

import requests
from tqdm import tqdm  # For showing progress

url = 'https://datasets.epfl.ch/w2s/W2S_raw.zip'
local_filename = 'W2S_raw.zip'

try:
    response = requests.get(url, stream=True)
    response.raise_for_status()  # Check for errors

    # Get the total file size for progress bar
    total_size = int(response.headers.get('content-length', 0))

    with open(local_filename, 'wb') as f, tqdm(
        desc=local_filename,
        total=total_size,
        unit='iB',
        unit_scale=True,
        unit_divisor=1024,
    ) as bar:
        for data in response.iter_content(chunk_size=1024):
            f.write(data)
            bar.update(len(data))

    print("Download completed successfully!")

except requests.exceptions.RequestException as e:
    print(f"An error occurred: {e}")
```

**Comment by majedelhelou** [comment]
The IT resolved this issue by increasing the download limits on the platform, regular downloading now works. 
All the best!
